FROM donbeave/debian-blockchain-build:1.0.0@sha256:41495d9ad42c2cf6145e24574e23d9a69cc571fe7b441253963a4d91367465d1 AS build

ARG SONIC_GETH_VERSION

RUN git clone --branch v${SONIC_GETH_VERSION} --single-branch --depth=1 https://github.com/0xsoniclabs/sonic

WORKDIR /sonic

RUN make all
# end build

FROM donbeave/debian-blockchain-base:1.0.0@sha256:bbd4761fdee07a4c30516b70857c4e86a0370061ade7aebaad24775a62ca4108

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY --from=build /sonic/build/sonicd /usr/local/bin/
COPY --from=build /sonic/build/sonictool /usr/local/bin/

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
