FROM --platform=arm64 donbeave/debian-blockchain-build:1.0.0@sha256:6071173e56543db5b775cc365263ec1fe29799add200984b10fa798f831fd17c AS build

ARG EIGENDA_PROXY_VERSION

RUN git clone --branch v${EIGENDA_PROXY_VERSION} --single-branch --depth=1 https://github.com/Layr-Labs/eigenda-proxy.git

WORKDIR /eigenda-proxy

RUN mise trust
RUN go mod download
RUN make build
# end build

FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:bbd4761fdee07a4c30516b70857c4e86a0370061ade7aebaad24775a62ca4108

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY --from=build /eigenda-proxy/bin/eigenda-proxy /usr/local/bin/
COPY --from=build /eigenda-proxy/resources/g1.point /var/lib/eigenda-proxy/resources/
COPY --from=build /eigenda-proxy/resources/g2.point /var/lib/eigenda-proxy/resources/
COPY --from=build /eigenda-proxy/resources/g2.trailing.point /var/lib/eigenda-proxy/resources/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
