FROM --platform=arm64 donbeave/debian-blockchain-build:1.0.0@sha256:41495d9ad42c2cf6145e24574e23d9a69cc571fe7b441253963a4d91367465d1 AS build

ARG EIGENDA_PROXY_VERSION

RUN git clone --branch v${EIGENDA_PROXY_VERSION} --single-branch --depth=1 https://github.com/Layr-Labs/eigenda-proxy.git

WORKDIR /eigenda-proxy

RUN mise trust
RUN go mod download
RUN make build
# end build

FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY --from=build /eigenda-proxy/bin/eigenda-proxy /usr/local/bin/
COPY --from=build /eigenda-proxy/resources/g1.point /var/lib/eigenda-proxy/resources/
COPY --from=build /eigenda-proxy/resources/g2.point /var/lib/eigenda-proxy/resources/
COPY --from=build /eigenda-proxy/resources/g2.trailing.point /var/lib/eigenda-proxy/resources/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
