FROM donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG LIGHTHOUSE_VERSION

RUN cd /tmp \
    && curl -L https://github.com/sigp/lighthouse/releases/download/v${LIGHTHOUSE_VERSION}/lighthouse-v${LIGHTHOUSE_VERSION}-x86_64-unknown-linux-gnu.tar.gz -o lighthouse.tar.gz \
    && tar -xvf lighthouse.tar.gz \
    && rm lighthouse.tar.gz \
    && mv lighthouse /usr/local/bin/ \
    && rm -rf /tmp/*

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
