FROM donbeave/debian-blockchain-base@sha256:ddbef80a9f6d007a7b5c0862b9b3e9a91cf3d95a84a778b74eecf9e3cee973ab

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG KCC_VERSION

RUN cd /tmp \
    && curl -L https://github.com/kcc-community/kcc/releases/download/v${KCC_VERSION}-stable/geth -o geth \
    && mv geth /usr/local/bin/geth \
    && chmod -v u+x /usr/local/bin/geth \
    && rm -rf /tmp/*

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
