FROM --platform=arm64 debian:trixie@sha256:5cf544fad978371b3df255b61e209b373583cb88b733475c86e49faa15ac2104

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ENV DEBIAN_FRONTEND=noninteractive
ENV XH_VERSION=0.25.0
ENV GOMPLATE_VERSION=4.3.3

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
               ca-certificates \
               curl \
               wget \
               git \
               unzip \
               xz-utils \
               procps \
               jq \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/* \
              /var/cache/apt/* \
              /tmp/*

RUN cd /tmp \
    && curl -L https://github.com/ducaale/xh/releases/download/v${XH_VERSION}/xh-v${XH_VERSION}-aarch64-unknown-linux-musl.tar.gz -o xh.tar.gz \
    && tar -xvf xh.tar.gz \
    && rm xh.tar.gz \
    && mv xh-*/xh /usr/local/bin/xh \
    && chmod a+x /usr/local/bin/xh \
    && rm -r xh-* \
    && rm -rf /tmp/*

RUN cd /tmp \
    && curl -L https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/gomplate_linux-arm64 -o gomplate \
    && mv gomplate /usr/local/bin/gomplate \
    && chmod a+x /usr/local/bin/gomplate \
    && rm -rf /tmp/*

RUN set -ex \
    && install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://mise.jdx.dev/gpg-key.pub -o /etc/apt/keyrings/mise.asc \
    && chmod a+r /etc/apt/keyrings/mise.asc

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/mise.asc] https://mise.jdx.dev/deb stable main" > /etc/apt/sources.list.d/mise.list

RUN set -ex \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
               mise \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/* \
              /var/cache/apt/* \
              /tmp/*

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV MISE_CONFIG_DIR=/opt/mise/config
ENV MISE_STATE_DIR=/opt/mise/state
ENV MISE_DATA_DIR=/opt/mise/data
ENV MISE_INSTALL_PATH=/usr/bin/mise

ENV PATH="/opt/mise/data/shims:$PATH"
