FROM donbeave/debian-blockchain-build:1.0.0@sha256:41495d9ad42c2cf6145e24574e23d9a69cc571fe7b441253963a4d91367465d1 AS build

RUN mise use -g --pin go@1.22.12

ARG SCROLL_GETH_VERSION

RUN git clone --branch scroll-v${SCROLL_GETH_VERSION} --single-branch --depth=1 https://github.com/scroll-tech/go-ethereum.git

WORKDIR /go-ethereum

RUN make nccc_geth
# end build

FROM donbeave/debian-blockchain-base:1.0.0@sha256:bbd4761fdee07a4c30516b70857c4e86a0370061ade7aebaad24775a62ca4108

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY --from=build /go-ethereum/build/bin/geth /usr/local/bin/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
