FROM donbeave/debian-blockchain-base@sha256:ad370c0a576cc58a8a4d3c34f96dc26a5a874f9c476224dd94afaae4789e2bba

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG BEACON_KIT_VERSION

RUN cd /tmp \
    && curl -L https://github.com/berachain/beacon-kit/releases/download/v${BEACON_KIT_VERSION}/beacond-v${BEACON_KIT_VERSION}-linux-amd64.tar.gz -o beacond.tar.gz \
    && tar -xzvf beacond.tar.gz \
    && rm beacond.tar.gz \
    && mv beacond-* /usr/local/bin/beacond \
    && chmod a+x /usr/local/bin/beacond \
    && rm -rf /tmp/*

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
