FROM --platform=arm64 donbeave/debian-blockchain-build:1.0.0@sha256:6071173e56543db5b775cc365263ec1fe29799add200984b10fa798f831fd17c AS build

ARG BOR_VERSION

RUN git clone --branch v${BOR_VERSION} --single-branch --depth=1 https://github.com/maticnetwork/bor.git

WORKDIR /bor

RUN make bor
# end build

FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY --from=build /bor/build/bin/bor /usr/local/bin/

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
