FROM --platform=arm64 donbeave/debian-blockchain-build:1.0.0@sha256:6071173e56543db5b775cc365263ec1fe29799add200984b10fa798f831fd17c AS build

ARG CELO_OP_GETH_VERSION

RUN git clone --branch celo-v${CELO_OP_GETH_VERSION} --single-branch --depth=1 https://github.com/celo-org/op-geth.git

WORKDIR /op-geth

RUN go run build/ci.go install -static ./cmd/geth
# end build

FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY --from=build /op-geth/build/bin/geth /usr/local/bin/

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
