FROM donbeave/debian-blockchain-base:1.0.0@sha256:bbd4761fdee07a4c30516b70857c4e86a0370061ade7aebaad24775a62ca4108

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG BSC_VERSION

RUN curl -L https://github.com/bnb-chain/bsc/releases/download/v${BSC_VERSION}/geth_linux -o /usr/local/bin/geth \
    && chmod -v u+x /usr/local/bin/geth

ADD config/config.toml /config/
ADD config/genesis.json /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
