FROM --platform=arm64 donbeave/debian-blockchain-build:1.0.0@sha256:41495d9ad42c2cf6145e24574e23d9a69cc571fe7b441253963a4d91367465d1 AS build

RUN mise use -g --pin go@1.22.12

ARG CELO_GETH_VERSION

RUN git clone --branch v${CELO_GETH_VERSION} --single-branch --depth=1 https://github.com/celo-org/celo-blockchain.git

WORKDIR /celo-blockchain

RUN make geth-musl
# end build

FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:bbd4761fdee07a4c30516b70857c4e86a0370061ade7aebaad24775a62ca4108

COPY --from=build /celo-blockchain/build/bin/geth /usr/local/bin/

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
