FROM donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG TRON_JAVA_VERSION

RUN apt-get update \
        && apt-get upgrade -y \
        && apt-get install -y --no-install-recommends \
                   libxi6 \
                   libxrender1 \
                   libxtst6 \
                   libasound2 \
                   libfreetype6 \
                   libfontconfig1 \
                   libgoogle-perftools4 \
        && apt-get autoremove -y \
        && rm -rf /var/lib/apt/* \
                  /var/cache/apt/* \
                  /tmp/*

ENV LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4"
ENV TCMALLOC_RELEASE_RATE=10

RUN cd /tmp \
    && curl -L https://download.bell-sw.com/java/8u432+7/bellsoft-jdk8u432+7-linux-amd64.deb -o liberica.deb \
    && dpkg -i liberica.deb \
    && rm liberica.deb \
    && rm -rf /tmp/*

RUN curl -L https://github.com/tronprotocol/java-tron/releases/download/GreatVoyage-v${TRON_JAVA_VERSION}/FullNode.jar -o /FullNode.jar

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data/tron-java
VOLUME /data
WORKDIR /data/tron-java

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
