FROM --platform=arm64 chainargos/debian-blockchain-base:1.0.0@sha256:060d1ab619195aa9003050a65124d38ae3f2f1ea1af5b62a983adc0713fd69a8

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG LITECOIN_CORE_VERSION

RUN cd /tmp \
    && curl -L https://github.com/litecoin-project/litecoin/releases/download/v${LITECOIN_CORE_VERSION}/litecoin-${LITECOIN_CORE_VERSION}-aarch64-linux-gnu.tar.gz -o litecoin.tar.gz \
    && tar -xvf litecoin.tar.gz \
    && rm litecoin.tar.gz \
    && mv litecoin-*/bin/* /usr/local/bin/ \
    && mv litecoin-*/share/* /usr/local/share/ \
    && rm -r litecoin-* \
    && rm -rf /tmp/*

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
