FROM --platform=arm64 donbeave/debian-blockchain-base@sha256:ad370c0a576cc58a8a4d3c34f96dc26a5a874f9c476224dd94afaae4789e2bba

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG LITECOIN_CORE_VERSION

RUN cd /tmp \
    && curl -L https://github.com/litecoin-project/litecoin/releases/download/v${LITECOIN_CORE_VERSION}/litecoin-${LITECOIN_CORE_VERSION}-aarch64-linux-gnu.tar.gz -o litecoin.tar.gz \
    && tar -xvf litecoin.tar.gz \
    && rm litecoin.tar.gz \
    && mv litecoin-*/bin/* /usr/local/bin/ \
    && mv litecoin-*/share/* /usr/local/share/ \
    && rm -r litecoin-* \
    && rm -rf /tmp/*

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
