FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG LITECOIN_CORE_VERSION

RUN cd /tmp \
    && curl -L https://github.com/litecoin-project/litecoin/releases/download/v${LITECOIN_CORE_VERSION}/litecoin-${LITECOIN_CORE_VERSION}-aarch64-linux-gnu.tar.gz -o litecoin.tar.gz \
    && tar -xvf litecoin.tar.gz \
    && rm litecoin.tar.gz \
    && mv litecoin-*/bin/* /usr/local/bin/ \
    && mv litecoin-*/share/* /usr/local/share/ \
    && rm -r litecoin-* \
    && rm -rf /tmp/*

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
