FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:bbd4761fdee07a4c30516b70857c4e86a0370061ade7aebaad24775a62ca4108

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG AVALANCHEGO_VERSION

RUN cd /tmp \
    && curl -L https://github.com/ava-labs/avalanchego/releases/download/v${AVALANCHEGO_VERSION}/avalanchego-linux-arm64-v${AVALANCHEGO_VERSION}.tar.gz -o avalanchego.tar.gz \
    && tar -xvf avalanchego.tar.gz \
    && rm avalanchego.tar.gz \
    && mv avalanchego-v${AVALANCHEGO_VERSION}/avalanchego /usr/local/bin/avalanchego \
    && rm -rf avalanchego-v${AVALANCHEGO_VERSION} \
    && chmod -v u+x /usr/local/bin/avalanchego \
    && rm -rf /tmp/*

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
