FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG AVALANCHEGO_VERSION

RUN cd /tmp \
    && curl -L https://github.com/ava-labs/avalanchego/releases/download/v${AVALANCHEGO_VERSION}/avalanchego-linux-arm64-v${AVALANCHEGO_VERSION}.tar.gz -o avalanchego.tar.gz \
    && tar -xvf avalanchego.tar.gz \
    && rm avalanchego.tar.gz \
    && mv avalanchego-v${AVALANCHEGO_VERSION}/avalanchego /usr/local/bin/avalanchego \
    && rm -rf avalanchego-v${AVALANCHEGO_VERSION} \
    && chmod -v u+x /usr/local/bin/avalanchego \
    && rm -rf /tmp/*

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
