FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:bbd4761fdee07a4c30516b70857c4e86a0370061ade7aebaad24775a62ca4108

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG DOGECOIN_CORE_VERSION

RUN cd /tmp \
    && curl -L https://github.com/dogecoin/dogecoin/releases/download/v${DOGECOIN_CORE_VERSION}/dogecoin-${DOGECOIN_CORE_VERSION}-aarch64-linux-gnu.tar.gz -o dogecoin.tar.gz \
    && tar -xvf dogecoin.tar.gz \
    && rm dogecoin.tar.gz \
    && mv dogecoin-*/bin/* /usr/local/bin/ \
    && mv dogecoin-*/include/* /usr/local/include/ \
    && mv dogecoin-*/lib/* /usr/local/lib/ \
    && mv dogecoin-*/share/* /usr/local/share/ \
    && rm -r dogecoin-* \
    && rm -rf /tmp/*

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
