FROM --platform=arm64 donbeave/debian-blockchain-build@sha256:1c21aa337d61d94ca5af3cb9441ade0a7ae0d814d1b822376fb40408928a9e05 AS build

ARG GITHUB_TOKEN

ARG OP_NODE_VERSION

RUN git clone --branch celo-v${OP_NODE_VERSION} --single-branch --depth=1 https://github.com/celo-org/optimism.git

WORKDIR /optimism

RUN mise trust
RUN mise config set settings.disable_tools --type list asterisc,kontrol,binary_signer
RUN mise install

RUN make op-node
# end build

FROM --platform=arm64 donbeave/debian-blockchain-base@sha256:ad370c0a576cc58a8a4d3c34f96dc26a5a874f9c476224dd94afaae4789e2bba

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY --from=build /optimism/op-node/bin/op-node /usr/local/bin/

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
