FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG BERA_GETH_VERSION
ARG BERA_GETH_COMMIT

RUN cd /tmp \
    && curl -L https://github.com/berachain/bera-geth/releases/download/v${BERA_GETH_VERSION}/bera-geth-alltools-linux-arm64-v${BERA_GETH_VERSION}-${BERA_GETH_COMMIT}.tar.gz -o geth.tar.gz \
    && tar -xvf geth.tar.gz \
    && rm geth.tar.gz \
    && rm bera-geth-*/COPYING \
    && mv bera-geth-*/* /usr/local/bin/ \
    && rm -r bera-geth-* \
    && rm -rf /tmp/*

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
