FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG GETH_VERSION

RUN cd /tmp \
    && curl -L https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-arm64-${GETH_VERSION}-${GIT_COMMIT}.tar.gz -o geth.tar.gz \
    && tar -xvf geth.tar.gz \
    && rm geth.tar.gz \
    && rm geth-*/COPYING \
    && mv geth-*/* /usr/local/bin/ \
    && rm -r geth-* \
    && rm -rf /tmp/*

RUN cd /tmp \
    && curl -L https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-arm64-${LEGACY_VERSION}-${LEGACY_GIT_COMMIT}.tar.gz -o geth.tar.gz \
    && tar -xvf geth.tar.gz \
    && rm geth.tar.gz \
    && rm geth-*/COPYING \
    && mv geth-* /opt/geth-1.13 \
    && rm -rf /tmp/*

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
