FROM --platform=arm64 donbeave/debian-blockchain-build:1.0.0@sha256:6071173e56543db5b775cc365263ec1fe29799add200984b10fa798f831fd17c AS build

ARG GNOSIS_GETH_VERSION

RUN git clone --branch v${GNOSIS_GETH_VERSION} --single-branch --depth=1 https://github.com/gnosischain/go-ethereum.git

WORKDIR /go-ethereum

RUN make geth
# end build

FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY --from=build /go-ethereum/build/bin/geth /usr/local/bin/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
