FROM donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG BITCOIN_CORE_VERSION

RUN cd /tmp \
    && curl -L "https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_CORE_VERSION}/bitcoin-${BITCOIN_CORE_VERSION}-x86_64-linux-gnu.tar.gz" -o bitcoin.tar.gz \
    && tar -xvf bitcoin.tar.gz \
    && rm bitcoin.tar.gz \
    && mv bitcoin-*/bin/* /usr/local/bin/ \
    && mv bitcoin-*/share/* /usr/local/share/ \
    && rm -r bitcoin-* \
    && rm -rf /tmp/*

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
