FROM donbeave/debian-blockchain-base@sha256:ddbef80a9f6d007a7b5c0862b9b3e9a91cf3d95a84a778b74eecf9e3cee973ab

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG BITCOIN_CORE_VERSION

RUN cd /tmp \
    && curl -L "https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_CORE_VERSION}/bitcoin-${BITCOIN_CORE_VERSION}-x86_64-linux-gnu.tar.gz" -o bitcoin.tar.gz \
    && tar -xvf bitcoin.tar.gz \
    && rm bitcoin.tar.gz \
    && mv bitcoin-*/bin/* /usr/local/bin/ \
    && mv bitcoin-*/share/* /usr/local/share/ \
    && rm -r bitcoin-* \
    && rm -rf /tmp/*

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
