FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

RUN cd /tmp \
    && curl -L https://gitlab.com/tezos/tezos/-/package_files/166078371/download -o octez.tar.gz \
    && tar -xvf octez.tar.gz \
    && rm octez.tar.gz \
    && mv octez-*/octez-node /usr/local/bin/ \
    && rm -rf octez-* \
    && chmod -v u+x /usr/local/bin/* \
    && rm -rf /tmp/*

RUN cd /tmp \
    && curl -L https://raw.githubusercontent.com/zcash/zcash/713fc761dd9cf4c9087c37b078bdeab98697bad2/zcutil/fetch-params.sh -o fetch-params.sh \
    && chmod +x fetch-params.sh \
    && ./fetch-params.sh \
    && rm fetch-params.sh \
    && rm -rf /tmp/*

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
