FROM donbeave/debian-blockchain-build:1.0.0@sha256:6071173e56543db5b775cc365263ec1fe29799add200984b10fa798f831fd17c AS build

ARG RONIN_GETH_VERSION

RUN git clone --branch v${RONIN_GETH_VERSION} --single-branch --depth=1 https://github.com/ronin-chain/ronin.git

WORKDIR /ronin

RUN make ronin
# end build

FROM donbeave/debian-blockchain-base:1.0.0@sha256:bbd4761fdee07a4c30516b70857c4e86a0370061ade7aebaad24775a62ca4108

COPY --from=build /ronin/build/bin/ronin /usr/local/bin/
COPY --from=build /ronin/genesis/mainnet.json /config/

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
