FROM --platform=arm64 offchainlabs/nitro-node:v3.9.2-52e8959@sha256:07baf4f937368c66eac7c113f5572854a5c486e36fa7da27f4ce36bfb370b8bb AS build

RUN ls
# end build

FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY --from=build /usr/local/bin/ /usr/local/bin/
COPY --from=build /home/user/target/machines /workspace/target/machines
COPY --from=build /home/user/nitro-legacy/machines /workspace/nitro-legacy/machines

RUN chown -R root:root /workspace/target/machines
RUN chown -R root:root /workspace/nitro-legacy/machines

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
