FROM --platform=arm64 offchainlabs/nitro-node:v3.9.2-52e8959@sha256:07baf4f937368c66eac7c113f5572854a5c486e36fa7da27f4ce36bfb370b8bb AS build

RUN ls
# end build

FROM --platform=arm64 donbeave/debian-blockchain-base@sha256:ddbef80a9f6d007a7b5c0862b9b3e9a91cf3d95a84a778b74eecf9e3cee973ab

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY --from=build /usr/local/bin/ /usr/local/bin/
COPY --from=build /home/user/target/machines /workspace/target/machines
COPY --from=build /home/user/nitro-legacy/machines /workspace/nitro-legacy/machines

RUN chown -R root:root /workspace/target/machines
RUN chown -R root:root /workspace/nitro-legacy/machines

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
