FROM donbeave/debian-blockchain-base@sha256:ad370c0a576cc58a8a4d3c34f96dc26a5a874f9c476224dd94afaae4789e2bba

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

ARG HECO_VERSION

RUN cd /tmp \
    && curl -L https://github.com/stars-labs/heco-chain/releases/download/v${HECO_VERSION}/geth-linux-amd64 -o geth \
    && mv geth /usr/local/bin/geth \
    && chmod -v u+x /usr/local/bin/geth \
    && rm -rf /tmp/*

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
