FROM donbeave/debian-blockchain-base:1.0.0@sha256:b6ce5ae5183425bc65547fedda6b4be0fa95879807a35e59ba5e4aa366131a9c AS build

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
               build-essential \
               linux-headers-amd64 \
               git \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/* \
              /var/cache/apt/* \
              /tmp/*

RUN mise install go@1.22.12
RUN mise install go@1.25.3

RUN mise use -g --pin go@1.25.3
