FROM --platform=arm64 donbeave/debian-blockchain-build:1.0.0@sha256:6071173e56543db5b775cc365263ec1fe29799add200984b10fa798f831fd17c AS build

ARG HEIMDALL_VERSION

RUN git clone --branch v${HEIMDALL_VERSION} --single-branch --depth=1 https://github.com/0xPolygon/heimdall-v2.git

WORKDIR /heimdall-v2

RUN make build-arm
# end build

FROM --platform=arm64 donbeave/debian-blockchain-base:1.0.0

LABEL org.opencontainers.image.authors="alexey@zhokhov.com"

COPY --from=build /heimdall-v2/build/heimdalld /usr/local/bin/

ADD config /config/

COPY start.sh /
RUN chmod a+x /start.sh

RUN mkdir -pv /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /
RUN chmod a+x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["/start.sh"]
